import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//High order component que contiene children
export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {/* <h2>Hola denuevo</h2> //Esto saldrá en todas las pantallas que tengamos. */}
        {children}
      </body>
    </html>
  );
}
